# Generated by Django 4.1.10 on 2023-11-13 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flat_name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "building_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "building_number",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("town", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("county", models.CharField(blank=True, max_length=100, null=True)),
                ("postcode", models.CharField(blank=True, max_length=8, null=True)),
                ("purchase_date", models.DateField()),
                ("purchase_price", models.IntegerField()),
                ("deposit", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payment_date", models.DateField(auto_created=True)),
                ("amount", models.IntegerField()),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="api.property",
                    ),
                ),
            ],
        ),
    ]
